require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArtpiecesController do

  # This should return the minimal set of attributes required to create a valid
  # Artpiece. As you add validations to Artpiece, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all artpieces as @artpieces" do
      artpiece = Artpiece.create! valid_attributes
      get :index
      assigns(:artpieces).should eq([artpiece])
    end
  end

  describe "GET show" do
    it "assigns the requested artpiece as @artpiece" do
      artpiece = Artpiece.create! valid_attributes
      get :show, :id => artpiece.id.to_s
      assigns(:artpiece).should eq(artpiece)
    end
  end

  describe "GET new" do
    it "assigns a new artpiece as @artpiece" do
      get :new
      assigns(:artpiece).should be_a_new(Artpiece)
    end
  end

  describe "GET edit" do
    it "assigns the requested artpiece as @artpiece" do
      artpiece = Artpiece.create! valid_attributes
      get :edit, :id => artpiece.id.to_s
      assigns(:artpiece).should eq(artpiece)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Artpiece" do
        expect {
          post :create, :artpiece => valid_attributes
        }.to change(Artpiece, :count).by(1)
      end

      it "assigns a newly created artpiece as @artpiece" do
        post :create, :artpiece => valid_attributes
        assigns(:artpiece).should be_a(Artpiece)
        assigns(:artpiece).should be_persisted
      end

      it "redirects to the created artpiece" do
        post :create, :artpiece => valid_attributes
        response.should redirect_to(Artpiece.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved artpiece as @artpiece" do
        # Trigger the behavior that occurs when invalid params are submitted
        Artpiece.any_instance.stub(:save).and_return(false)
        post :create, :artpiece => {}
        assigns(:artpiece).should be_a_new(Artpiece)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Artpiece.any_instance.stub(:save).and_return(false)
        post :create, :artpiece => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested artpiece" do
        artpiece = Artpiece.create! valid_attributes
        # Assuming there are no other artpieces in the database, this
        # specifies that the Artpiece created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Artpiece.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => artpiece.id, :artpiece => {'these' => 'params'}
      end

      it "assigns the requested artpiece as @artpiece" do
        artpiece = Artpiece.create! valid_attributes
        put :update, :id => artpiece.id, :artpiece => valid_attributes
        assigns(:artpiece).should eq(artpiece)
      end

      it "redirects to the artpiece" do
        artpiece = Artpiece.create! valid_attributes
        put :update, :id => artpiece.id, :artpiece => valid_attributes
        response.should redirect_to(artpiece)
      end
    end

    describe "with invalid params" do
      it "assigns the artpiece as @artpiece" do
        artpiece = Artpiece.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Artpiece.any_instance.stub(:save).and_return(false)
        put :update, :id => artpiece.id.to_s, :artpiece => {}
        assigns(:artpiece).should eq(artpiece)
      end

      it "re-renders the 'edit' template" do
        artpiece = Artpiece.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Artpiece.any_instance.stub(:save).and_return(false)
        put :update, :id => artpiece.id.to_s, :artpiece => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested artpiece" do
      artpiece = Artpiece.create! valid_attributes
      expect {
        delete :destroy, :id => artpiece.id.to_s
      }.to change(Artpiece, :count).by(-1)
    end

    it "redirects to the artpieces list" do
      artpiece = Artpiece.create! valid_attributes
      delete :destroy, :id => artpiece.id.to_s
      response.should redirect_to(artpieces_url)
    end
  end

end
